name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: BOM.Frontend
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: cloudquicklabsacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . --file /BOM.Frontend/apps/employer/Dockerfile -t cloudquicklabsacr.azurecr.io/myapp:${{ github.sha }}
        docker push cloudquicklabsacr.azurecr.io/myapp:${{ github.sha }}
